---
- hosts: all
  tasks: 
    - name: check wether apache2 is present
      apt: 
        name: apache2
        state: present
      register: apache2_is_present
      become: true
    - name: remove apache2
      block: 
        - name: executer whereis
          become: true
          shell: whereis apache2
          register: whereisoutput
        - name: echo whereis output
          debug:
            msg: "output => {{whereisoutput.stdout | replace('apache2: ', '')}}"
      when: apache2_is_present is defined